[workspace]
members = [
    "src/bin/decker-cli",
    "src/bin/decker-qml",
    "src/lib/decker-lib",
    "src/lib/decker-helpers",
    "src/lib/repositories/sqlite-repository",
    "src/lib/filesystem-operations/vfs-filesystem-operations",
    "src/games/openmw",
]
